---
title: "laptops"
author: "Hindy Rossignol"
date: "2025-09-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # 
```

```{r}

# Import packages

install.packages("readr")
install.packages("dplyr")
```
```{r}
library(readr)
library(dplyr)
```

```{r}
df_train <- read_csv("/Users/hindy/Desktop/Academics/MIT/MIT MBAn/Advanced Analytics Edge /Homeworks/deliverable1-analyticsedge-mit/Data/laptop_train.csv")

df_test <- read_csv("/Users/hindy/Desktop/Academics/MIT/MIT MBAn/Advanced Analytics Edge /Homeworks/deliverable1-analyticsedge-mit/Data/laptop_test.csv")
```
```{r}
head(df_train)    
head(df_test)
```
```{r}
# We want to know the dimensions of our dataset. 
dim(df_train) # there are 9 features and 665 observations
dim(df_test) # there are 9 features and 280 observations
```

```{r}
str(df_train)  # structure (variable types, first few entries)
str(df_test)
```

```{r}
summary(df_train)        # summary statistics by column
summary(df_test)
```

```{r}
colSums(is.na(df_train))   # number of NAs per column
anyNA(df_train)            # check if dataset has any missing values
```





















