---
title: "laptops"
author: "Hindy Rossignol, Riya Parikh, Mrugank Pednekar, Ioannis Panagiotopoulos"
date: "2025-09-11"
output: html_document
---
### R setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

```{r}

# Import packages

install.packages("readr")
install.packages("dplyr")
```
```{r}
library(readr)
library(dplyr)
```
### Problem 1
```{r}
df_train <- read_csv("/Users/riyaparikh_computeracct/Downloads/MIT/15.072_AdvancedAnalyticsEdge  /deliverable1-analyticsedge-mit/Data//laptop_train.csv")

df_test <- read_csv("/Users/riyaparikh_computeracct/Downloads/MIT/15.072_AdvancedAnalyticsEdge  /deliverable1-analyticsedge-mit/Data/laptop_test.csv")
```
```{r}
head(df_train)    
head(df_test)
```
```{r}
# We want to know the dimensions of our dataset. 
dim(df_train) # there are 9 features and 665 observations
dim(df_test) # there are 9 features and 280 observations
```

```{r}
str(df_train)  # structure (variable types, first few entries)
str(df_test)
```

```{r}
summary(df_train)        # summary statistics by column
summary(df_test)
```

```{r}
colSums(is.na(df_train))   # number of NAs per column
anyNA(df_train)            # check if dataset has any missing values
```

### Problem 2
```{r part a}
# loading df
df_insurance <- read_csv("/Users/riyaparikh_computeracct/Downloads/MIT/15.072_AdvancedAnalyticsEdge  /deliverable1-analyticsedge-mit/Data/insurance.csv", show_col_types = FALSE)
```

```{r part b}
# mean = 13270.42, sd = 12110.01
mean_charges = mean(df_insurance$charges)
sd_charges = sd(df_insurance$charges)
```

```{r part c}
# probability of being btwn 8k 14k based on normal distribution is 0.19
probability_between_values = pnorm(14000, mean_charges, sd_charges) - pnorm(8000, mean_charges, sd_charges)
```

```{r part d}
# actual proportion of charges between 8k, 14k is 0.28. this is not the same as the probability we got when assuming the charges follow a normal distribution in part c. our initial assumption is that the charges do not follow a Normal distribution. the histogram we plotted of charges data points shows that the distribution is right skewed towards higher charges. we also see that the median charge is lower than the mean charge ($9382.033 vs $13270.42).
count_in_range <- sum(df_insurance$charges >= 8000 & df_insurance$charges <= 14000)
total_vals = length(df_insurance$charges)
true_prop_between_values = count_in_range/total_vals
median(df_insurance$charges)

hist(df_insurance$charges, main = "Histogram of Charges Data Points", xlab = "Data Point Value", col = "skyblue")
```

```{r part e}
# based on both statistical metrics and visual diagnostics, the lognormal distribution is the best fit for the charges data. lognormal wins across all metrics, especially the goodness-of-fit statistics. the KS statistic is significantly lower for lognormal, indicating a closer match between empirical and theoretical distributions. the quantile comparison shows that lognormal quantiles closely match the actual data. refining part d, the insurance charges data is not normally distributed. instead, it follows a log-normal distribution, which better captures the right-skew in the data and aligns more closely with observed quantiles and proportions.
install.packages("fitdistrplus")
library(fitdistrplus)

fit_norm <- fitdist(df_insurance$charges, "norm")
fit_lognorm <- fitdist(df_insurance$charges, "lnorm")
fit_unif <- fitdist(df_insurance$charges, "unif")
fit_cauchy <- fitdist(df_insurance$charges, "cauchy")

gofstat(list(fit_norm, fit_lognorm, fit_unif, fit_cauchy))

plot.legend <- c("Normal", "Lognormal", "Uniform", "Cauchy")
denscomp(list(fit_norm, fit_lognorm, fit_unif, fit_cauchy), legendtext = plot.legend)
cdfcomp(list(fit_norm, fit_lognorm, fit_unif, fit_cauchy), legendtext = plot.legend)
qqcomp(list(fit_norm, fit_lognorm, fit_unif, fit_cauchy), legendtext = plot.legend)

quantile(df_insurance$charges, probs = c(0.25, 0.5, 0.75))
qlnorm(c(0.25, 0.5, 0.75), meanlog = fit_lognorm$estimate["meanlog"], sdlog = fit_lognorm$estimate["sdlog"])
```

```{r part f}
mod <-  lm(charges ~ age + factor(sex) + bmi + children + factor(smoker) + factor(region) , data = df_insurance)
summary_mod = summary(mod)
```

```{r part g}
## it is important to note that for the following interpretations, the change per unit that is being described only holds true if all other factors are held constant. 

## age: for every increase of 1 yr in age, the charges are predicted to increase by $256.9, holding other variables constant. this variable is statistically significant as the pvalue is <0.05 at 2e-16.

## factor(sex)male: being a male, the charges are predicted to be lower by $131.3 compared to their equivalent female counterparts, holding other variables constant. this variable is not statistically significant as the pvalue is >0.05 at 0.693348.

## bmi: for every increase of 1 unit in bmi, the charges are predicted to increase by $339.2, holding other variables constant. this variable is statistically significant as the pvalue is <0.05 at 2e-16.

## children: for every additional child the customer has, the charges are predicted to increase by $475.5, holding other variables constant. this variable is statistically significant as the pvalue is <0.05 at 0.000577.

## factor(smoker)yes: being a smoker, the charges are predicted to be higher by $23848.5 compared to their nonsmoking counterparts, holding other variables constant. this variable is statistically significant as the pvalue is <0.05 at 2e-16.

## factor(region)northwest: if a customer lives in the northwest, their charges are predicted to be lower by $353.0 holding all other variables constant. this variable is not statistically significant as the pvalue is <0.05 at 0.458769.

## factor(region)southeast: if a customer lives in the southeast, their charges are predicted to be lower by $1035.0 holding all other variables constant. this variable is statistically significant as the pvalue is <0.05 at 0.030782.

## factor(region)southwest:  if a customer lives in the southwest, their charges are predicted to be lower by $960.0 holding all other variables constant. this variable is statistically significant as the pvalue is <0.05 at 0.044765.
```

```{r}
# part h - Comment on whether you think some age groups are more likely to be undercharged or overcharged when age is not considered as an independent variable.
mod2 <-  lm(charges ~ factor(sex) + bmi + children + factor(smoker) + factor(region) , data = df_insurance)
summary_mod2 = summary(mod2)
# the first model had an r^2 of .751 meaning that 75.1% of the variation in charges is accounted for by the model built on all the factors. the adj r^2 is .749.
# the second model (built without age) has an r^2 of .664 meaning that 66.4% of the variation in charges is accounted for by the model built on all the factors without age. the adj r^2 is .662.
# when age is not considered as an independent variable,  the model is forced to "spread" the influence of age across other variables like BMI, smoking status, and region. younger individuals are likely to be overcharged: without age, the model can't distinguish between a healthy 25-year-old and a 55-year-old with similar BMI and smoking status. older individuals are likely to be undercharged: older individuals typically incur higher medical costs, which the model without age can't fully capture.
```

```{r}
# part i - would recommend applying a log transformation to the charges variable, and then redoing the analysis using the transformed variable to assess linear relationships and model assumptions more effectively.
```



















